In [55]:
import pandas as pd
from imblearn.under_sampling import RandomUnderSampler
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE

In [56]:
def oversampling(df_data, seed):
    X = df_data.drop('target', axis=1)
    y = df_data['target']  
    #Se definen los objetos para sobremuestrear
    smote = SMOTE(random_state=seed)

    #Se aplica el sobremuestreo
    X_res, y_res= smote.fit_resample(X, y)
    df_resampled = pd.concat([X_res,y_res], axis=1)
    
    return df_resampled

In [57]:
def function_split(df_data, seed):
    #Separa los datos
    data_under= oversampling(df_data, seed)
    train_data_under, val_data_under = train_test_split(data_under, test_size=0.2, random_state=seed)
    return data_under, train_data_under, val_data_under

In [58]:
repr_name="ProtT5"
df_data = pd.read_csv(f"../../data/numerical_rep/{repr_name}.csv")
df_data.drop(["experimental_characteristics"], axis=1, inplace=True)

In [59]:
data_under, df_train_under, df_val_under = function_split(df_data, seed=42)

In [60]:
ten_percent=df_data[df_data["target"]==2].sample(frac=0.10, random_state=42)
X=df_data.drop('target', axis=1)
y=df_data['target']  
#Se definen los objetos para submuestrear
X['index']=X.index 
undersampler=RandomUnderSampler(sampling_strategy='not minority', random_state=42)    

#Se aplica el submuestreo
X_res, y_res=undersampler.fit_resample(X, y)
df_resampled=pd.concat([X_res,y_res], axis=1)

index_res=X_res['index']

mask=~X['index'].isin(index_res)
excluded_data=df_data[mask.values]
data_independent= pd.concat([ten_percent, excluded_data], axis=0)
data_independent.reset_index(drop=True, inplace=True)

In [67]:
ten_percent

,p_1,p_2,p_3,p_4,p_5,p_6,p_7,p_8,p_9,p_10,...,p_1018,p_1019,p_1020,p_1021,p_1022,p_1023,p_1024,target,half_life_seconds,length_sequence
697,-0.161156,-0.042202,0.033214,-0.003554,0.114623,0.084499,0.010926,0.037314,0.087718,-0.134897,...,0.022629,-0.011691,0.000537,0.162795,0.060449,0.051164,-0.136712,2,19800.0,18
876,-0.124421,-0.092659,-0.039010,0.049755,0.106497,0.023749,-0.073537,0.136418,0.035264,0.018531,...,-0.071090,-0.005242,-0.018944,0.127926,-0.094337,0.132509,-0.147119,2,36000.0,46
308,-0.163448,-0.071376,-0.073080,-0.047339,0.061322,-0.027039,-0.115078,0.048614,0.005866,-0.082186,...,-0.004933,-0.025708,0.064287,0.138789,-0.021012,0.066337,-0.109928,2,36000.0,36
1092,0.102921,0.138724,-0.047114,0.021421,-0.127769,0.036998,-0.093082,-0.015085,-0.061599,0.100188,...,-0.018288,0.026866,-0.098394,0.112487,-0.001131,0.088987,-0.033823,2,25920.0,19
1107,-0.057185,0.045712,-0.060396,-0.039427,-0.118452,-0.049181,-0.025291,0.034324,-0.139513,-0.065778,...,0.007965,0.144676,0.042604,0.129047,-0.003082,0.046553,-0.013087,2,25920.0,20
1077,-0.011931,0.009440,-0.032912,-0.082046,0.174595,-0.090601,-0.100539,0.032651,-0.026741,-0.030523,...,0.090868,-0.090027,0.019689,0.178556,-0.020832,-0.017221,-0.121947,2,25920.0,12
1091,0.088363,0.057953,-0.003353,0.058218,-0.130642,0.136867,-0.064486,-0.043539,-0.021134,0.143219,...,-0.071721,-0.020714,-0.052536,0.130675,-0.065124,0.092816,-0.029841,2,25920.0,19
325,-0.095115,-0.072286,-0.095639,-0.058678,0.064860,-0.063347,-0.276587,0.104825,0.067443,-0.027673,...,0.069607,-0.041802,-0.024189,0.103612,-0.114725,0.116017,-0.045304,2,72000.0,20
312,-0.069232,-0.106906,-0.192574,-0.084646,-0.020822,-0.071778,-0.080395,0.004814,0.023902,0.045280,...,0.038167,-0.084574,0.076757,0.228894,-0.021710,0.057009,-0.130213,2,36000.0,25
1118,-0.056959,0.031147,-0.038356,0.002008,-0.005682,-0.040978,-0.034128,0.057850,-0.044719,0.004852,...,0.029328,0.062342,-0.000056,0.071573,-0.091921,0.031729,-0.037693,2,25920.0,15
1109,-0.023732,0.064834,-0.021404,-0.066099,0.099363,0.063713,-0.068782,-0.048475,0.033077,-0.082787,...,0.100231,0.001636,-0.119101,0.244457,-0.065660,0.165433,-0.091082,2,25920.0,20
305,-0.053989,0.000303,-0.043287,-0.048095,-0.060453,-0.070076,0.103917,0.023853,0.030663,-0.171439,...,0.006242,0.080310,0.008751,0.136003,0.036057,0.117760,-0.134955,2,36000.0,14
668,-0.053680,0.091168,-0.111352,-0.090398,-0.052651,0.072519,0.011285,0.102023,0.051110,-0.045090,...,-0.012799,0.022396,0.049519,0.066318,-0.006496,0.166667,-0.073544,2,19800.0,20
670,0.031755,0.118700,-0.094433,-0.011750,-0.143280,-0.006750,-0.020171,0.119047,0.036932,-0.036561,...,0.068467,0.067504,0.090867,0.090993,0.046801,0.107032,0.008021,2,19800.0,20
878,-0.056652,0.093191,-0.074798,-0.022411,-0.051831,-0.027593,-0.008201,0.062034,-0.001823,-0.004938,...,-0.069629,0.078602,0.021545,0.078220,-0.097918,0.064036,-0.028000,2,36000.0,15
638,-0.045174,0.005221,-0.130705,0.034413,-0.037079,-0.012907,-0.149961,0.125597,-0.027898,0.019330,...,0.050977,-0.005481,0.049427,0.057522,0.005445,0.039807,-0.128907,2,19800.0,37
1075,-0.116734,0.059453,-0.040848,-0.036597,0.183925,-0.133701,-0.229284,-0.019606,0.015560,-0.032546,...,0.094539,-0.053503,0.059763,0.149303,-0.116596,0.060268,-0.067443,2,25920.0,12
293,-0.023260,-0.082462,-0.105519,0.047516,0.117883,-0.039932,-0.113248,0.042390,-0.017235,0.003760,...,0.071738,0.025877,0.014384,0.253875,-0.100374,0.158527,-0.079262,2,36000.0,12
1098,-0.069478,-0.089589,-0.240362,0.019737,-0.022484,0.103280,0.081951,0.054007,-0.043759,-0.095346,...,0.097600,0.038419,-0.062128,0.181843,0.050832,0.107703,-0.156934,2,25920.0,12
757,-0.045380,0.068380,-0.072362,-0.025747,-0.059018,0.002201,-0.053504,0.098960,-0.035360,-0.014073,...,0.008917,-0.013104,-0.026350,0.076355,-0.121158,0.141463,-0.037241,2,19800.0,17

In [66]:
excluded_data

,p_1,p_2,p_3,p_4,p_5,p_6,p_7,p_8,p_9,p_10,...,p_1018,p_1019,p_1020,p_1021,p_1022,p_1023,p_1024,target,half_life_seconds,length_sequence
0,0.024928,0.038137,0.010136,0.013962,0.003674,-0.054007,0.023122,0.204115,-0.129186,-0.162114,...,0.107394,0.060945,0.010294,0.168054,-0.020148,0.067316,-0.133364,1,15840.0,9
2,0.056347,-0.045785,-0.013331,-0.050032,-0.088194,-0.073964,-0.068582,0.031079,-0.001762,-0.124785,...,0.120435,0.018659,0.031999,0.077117,-0.017236,0.066621,-0.089538,1,15840.0,9
4,-0.105726,0.069741,-0.127632,-0.124845,0.202506,0.030408,-0.049978,0.130994,0.033893,0.089469,...,0.066739,-0.082009,-0.066162,0.287695,0.050576,0.212813,0.008588,1,15840.0,21
5,-0.093197,0.017146,-0.194195,0.039948,0.116347,0.048788,-0.115615,0.071225,0.001501,-0.111091,...,0.080442,-0.074865,0.045370,0.115240,0.027045,0.002599,-0.129619,1,15840.0,35
6,-0.106681,0.056686,-0.121383,-0.005295,0.132930,0.068102,0.037182,0.165086,-0.112650,-0.106992,...,-0.020315,0.148110,-0.017341,0.212725,0.052870,0.111671,-0.073885,1,15840.0,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1306,-0.100075,0.001455,0.017908,0.044346,-0.079563,0.011130,-0.021392,0.009696,0.048142,0.042567,...,0.100753,-0.029305,0.093444,0.089840,0.031600,0.066225,-0.084514,0,7200.0,20
1308,-0.100075,0.001455,0.017908,0.044346,-0.079563,0.011130,-0.021392,0.009696,0.048142,0.042567,...,0.100753,-0.029305,0.093444,0.089840,0.031600,0.066225,-0.084514,1,10080.0,20
1309,-0.117940,0.047649,-0.007363,-0.014420,0.019296,0.058130,-0.071593,0.036150,0.075177,-0.137731,...,0.018345,0.036152,-0.014890,0.138495,-0.086376,0.005198,-0.064887,0,7200.0,18
1310,-0.203825,0.062788,0.006884,-0.049276,0.067048,0.083548,-0.154984,0.052247,0.098920,-0.150795,...,0.023684,0.065029,0.002418,0.121806,-0.107974,-0.035496,-0.073660,1,10080.0,18
1312,0.018352,0.024859,-0.086066,-0.049379,-0.051685,-0.033973,-0.068558,0.018888,0.002944,-0.037312,...,0.097688,0.059441,0.030448,0.061154,-0.083948,0.079395,-0.027652,0,7200.0,9

In [61]:
data_independent

,p_1,p_2,p_3,p_4,p_5,p_6,p_7,p_8,p_9,p_10,...,p_1018,p_1019,p_1020,p_1021,p_1022,p_1023,p_1024,target,half_life_seconds,length_sequence
0,-0.161156,-0.042202,0.033214,-0.003554,0.114623,0.084499,0.010926,0.037314,0.087718,-0.134897,...,0.022629,-0.011691,0.000537,0.162795,0.060449,0.051164,-0.136712,2,19800.0,18
1,-0.124421,-0.092659,-0.039010,0.049755,0.106497,0.023749,-0.073537,0.136418,0.035264,0.018531,...,-0.071090,-0.005242,-0.018944,0.127926,-0.094337,0.132509,-0.147119,2,36000.0,46
2,-0.163448,-0.071376,-0.073080,-0.047339,0.061322,-0.027039,-0.115078,0.048614,0.005866,-0.082186,...,-0.004933,-0.025708,0.064287,0.138789,-0.021012,0.066337,-0.109928,2,36000.0,36
3,0.102921,0.138724,-0.047114,0.021421,-0.127769,0.036998,-0.093082,-0.015085,-0.061599,0.100188,...,-0.018288,0.026866,-0.098394,0.112487,-0.001131,0.088987,-0.033823,2,25920.0,19
4,-0.057185,0.045712,-0.060396,-0.039427,-0.118452,-0.049181,-0.025291,0.034324,-0.139513,-0.065778,...,0.007965,0.144676,0.042604,0.129047,-0.003082,0.046553,-0.013087,2,25920.0,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
734,-0.100075,0.001455,0.017908,0.044346,-0.079563,0.011130,-0.021392,0.009696,0.048142,0.042567,...,0.100753,-0.029305,0.093444,0.089840,0.031600,0.066225,-0.084514,0,7200.0,20
735,-0.100075,0.001455,0.017908,0.044346,-0.079563,0.011130,-0.021392,0.009696,0.048142,0.042567,...,0.100753,-0.029305,0.093444,0.089840,0.031600,0.066225,-0.084514,1,10080.0,20
736,-0.117940,0.047649,-0.007363,-0.014420,0.019296,0.058130,-0.071593,0.036150,0.075177,-0.137731,...,0.018345,0.036152,-0.014890,0.138495,-0.086376,0.005198,-0.064887,0,7200.0,18
737,-0.203825,0.062788,0.006884,-0.049276,0.067048,0.083548,-0.154984,0.052247,0.098920,-0.150795,...,0.023684,0.065029,0.002418,0.121806,-0.107974,-0.035496,-0.073660,1,10080.0,18
738,0.018352,0.024859,-0.086066,-0.049379,-0.051685,-0.033973,-0.068558,0.018888,0.002944,-0.037312,...,0.097688,0.059441,0.030448,0.061154,-0.083948,0.079395,-0.027652,0,7200.0,9

In [62]:
excluded_data[excluded_data["target"]==1]

,p_1,p_2,p_3,p_4,p_5,p_6,p_7,p_8,p_9,p_10,...,p_1018,p_1019,p_1020,p_1021,p_1022,p_1023,p_1024,target,half_life_seconds,length_sequence
0,0.024928,0.038137,0.010136,0.013962,0.003674,-0.054007,0.023122,0.204115,-0.129186,-0.162114,...,0.107394,0.060945,0.010294,0.168054,-0.020148,0.067316,-0.133364,1,15840.0,9
2,0.056347,-0.045785,-0.013331,-0.050032,-0.088194,-0.073964,-0.068582,0.031079,-0.001762,-0.124785,...,0.120435,0.018659,0.031999,0.077117,-0.017236,0.066621,-0.089538,1,15840.0,9
4,-0.105726,0.069741,-0.127632,-0.124845,0.202506,0.030408,-0.049978,0.130994,0.033893,0.089469,...,0.066739,-0.082009,-0.066162,0.287695,0.050576,0.212813,0.008588,1,15840.0,21
5,-0.093197,0.017146,-0.194195,0.039948,0.116347,0.048788,-0.115615,0.071225,0.001501,-0.111091,...,0.080442,-0.074865,0.045370,0.115240,0.027045,0.002599,-0.129619,1,15840.0,35
6,-0.106681,0.056686,-0.121383,-0.005295,0.132930,0.068102,0.037182,0.165086,-0.112650,-0.106992,...,-0.020315,0.148110,-0.017341,0.212725,0.052870,0.111671,-0.073885,1,15840.0,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1290,-0.018477,0.036644,-0.065536,-0.047132,0.059413,-0.043447,-0.137613,0.167634,-0.024995,-0.003401,...,0.040275,0.031785,0.029382,0.177697,-0.158631,0.128693,-0.103173,1,10080.0,12
1296,-0.157828,0.080220,-0.134509,-0.024411,-0.009210,0.072394,-0.058482,0.053240,0.077067,0.084828,...,0.081755,0.018977,0.136174,0.076200,-0.093582,0.033571,-0.195850,1,10080.0,20
1303,-0.098615,-0.091629,-0.020671,-0.007833,0.059455,0.046928,-0.202553,0.034373,0.059682,0.020352,...,0.001195,-0.016447,0.030442,0.086734,-0.125661,0.110023,-0.169574,1,10080.0,36
1308,-0.100075,0.001455,0.017908,0.044346,-0.079563,0.011130,-0.021392,0.009696,0.048142,0.042567,...,0.100753,-0.029305,0.093444,0.089840,0.031600,0.066225,-0.084514,1,10080.0,20
1310,-0.203825,0.062788,0.006884,-0.049276,0.067048,0.083548,-0.154984,0.052247,0.098920,-0.150795,...,0.023684,0.065029,0.002418,0.121806,-0.107974,-0.035496,-0.073660,1,10080.0,18

In [63]:
df_resampled.value_counts("target")

target
0    198
1    198
2    198
dtype: int64

In [64]:
df_train_under.value_counts("target")

target
2    550
0    545
1    532
dtype: int64

In [65]:
df_val_under.value_counts("target")

target
1    146
0    133
2    128
dtype: int64