In [104]:
import pandas as pd
import os
import re

In [105]:
path = "metrics/"

In [106]:
csv_files = [f for f in os.listdir(path) if f.endswith(".csv") and "Grid" not in f]

dfs = []

In [107]:
def extract_representation(filename):
    name = filename.replace(".csv", "")
    return name.replace("antiviral_homology_90_", "").replace("antiviral_homology_90", "")

# Leer y etiquetar
for file in csv_files:
    df = pd.read_csv(os.path.join(path, file))
    df["representation"] = extract_representation(file)
    dfs.append(df)

In [108]:
combined_df = pd.concat(dfs, ignore_index=True)
combined_df

,accuracy,recall,precision,f1,roc_auc_ovr,mcc,fit_time,score_time,Dataset,model,sampling,representation
0,0.484848,0.484848,0.443001,0.442482,0.630013,0.060165,3.879821,0.019060,Validation,AdaBoost,Original,embedding_protT5_AdaBoost_42_metrics
1,0.477273,0.477273,0.403992,0.421904,0.571139,0.037489,3.812454,0.018698,Validation,AdaBoost,Original,embedding_protT5_AdaBoost_42_metrics
2,0.484848,0.484848,0.451658,0.462005,0.532409,0.100497,3.866243,0.019695,Validation,AdaBoost,Original,embedding_protT5_AdaBoost_42_metrics
3,0.503817,0.503817,0.447038,0.453395,0.549619,0.081538,3.890284,0.019236,Validation,AdaBoost,Original,embedding_protT5_AdaBoost_42_metrics
4,0.480916,0.480916,0.437114,0.452126,0.563241,0.069637,3.881790,0.019112,Validation,AdaBoost,Original,embedding_protT5_AdaBoost_42_metrics
...,...,...,...,...,...,...,...,...,...,...,...,...
9295,0.608411,0.608411,0.605959,0.598003,0.779069,0.419501,0.722411,0.043744,Train,SVM,Over,pc_ZIMJ680104_SVM_42_metrics
9296,0.610595,0.610595,0.608655,0.599333,0.780626,0.423613,0.720591,0.044282,Train,SVM,Over,pc_ZIMJ680104_SVM_42_metrics
9297,0.614418,0.614418,0.610625,0.605568,0.778592,0.426866,0.720486,0.044384,Train,SVM,Over,pc_ZIMJ680104_SVM_42_metrics
9298,0.614965,0.614965,0.611807,0.601820,0.780552,0.431140,0.716101,0.043799,Train,SVM,Over,pc_ZIMJ680104_SVM_42_metrics
9299,0.621518,0.621518,0.620709,0.612204,0.783040,0.439112,0.717943,0.043943,Train,SVM,Over,pc_ZIMJ680104_SVM_42_metrics

In [109]:
not_trained=combined_df[combined_df["Dataset"] != "Train"]

In [110]:
not_trained

,accuracy,recall,precision,f1,roc_auc_ovr,mcc,fit_time,score_time,Dataset,model,sampling,representation
0,0.484848,0.484848,0.443001,0.442482,0.630013,0.060165,3.879821,0.019060,Validation,AdaBoost,Original,embedding_protT5_AdaBoost_42_metrics
1,0.477273,0.477273,0.403992,0.421904,0.571139,0.037489,3.812454,0.018698,Validation,AdaBoost,Original,embedding_protT5_AdaBoost_42_metrics
2,0.484848,0.484848,0.451658,0.462005,0.532409,0.100497,3.866243,0.019695,Validation,AdaBoost,Original,embedding_protT5_AdaBoost_42_metrics
3,0.503817,0.503817,0.447038,0.453395,0.549619,0.081538,3.890284,0.019236,Validation,AdaBoost,Original,embedding_protT5_AdaBoost_42_metrics
4,0.480916,0.480916,0.437114,0.452126,0.563241,0.069637,3.881790,0.019112,Validation,AdaBoost,Original,embedding_protT5_AdaBoost_42_metrics
...,...,...,...,...,...,...,...,...,...,...,...,...
9285,0.610837,0.610837,0.608229,0.601356,0.753883,0.421686,0.722411,0.043744,Validation,SVM,Over,pc_ZIMJ680104_SVM_42_metrics
9286,0.600985,0.600985,0.602131,0.583931,0.750965,0.413628,0.720591,0.044282,Validation,SVM,Over,pc_ZIMJ680104_SVM_42_metrics
9287,0.630542,0.630542,0.630681,0.622850,0.751090,0.451617,0.720486,0.044384,Validation,SVM,Over,pc_ZIMJ680104_SVM_42_metrics
9288,0.571429,0.571429,0.578508,0.564982,0.750680,0.364568,0.716101,0.043799,Validation,SVM,Over,pc_ZIMJ680104_SVM_42_metrics
9289,0.551724,0.551724,0.543590,0.541283,0.722668,0.332128,0.717943,0.043943,Validation,SVM,Over,pc_ZIMJ680104_SVM_42_metrics

In [111]:
mean_grouped = not_trained.groupby(["Dataset", "model", "sampling","representation"]).mean(numeric_only=True)
mean_grouped = mean_grouped.reset_index()

In [112]:
mean_grouped

,Dataset,model,sampling,representation,accuracy,recall,precision,f1,roc_auc_ovr,mcc,fit_time,score_time
0,Validation,AdaBoost,Original,embedding_protT5_AdaBoost_42_metrics,0.476758,0.476758,0.418585,0.431933,0.580661,0.045282,3.863201,0.018928
1,Validation,AdaBoost,Original,fft_FASG760101_AdaBoost_42_metrics,0.517129,0.517129,0.430620,0.437165,0.600029,0.080455,0.197474,0.021925
2,Validation,AdaBoost,Original,fft_FAUJ880111_AdaBoost_42_metrics,0.512619,0.512619,0.369739,0.419003,0.602807,0.058860,0.077618,0.019051
3,Validation,AdaBoost,Original,fft_FAUJ880112_AdaBoost_42_metrics,0.515614,0.515614,0.302504,0.362066,0.547311,0.006616,0.076301,0.017649
4,Validation,AdaBoost,Original,fft_GEIM800101_AdaBoost_42_metrics,0.509467,0.509467,0.458909,0.439578,0.591760,0.072117,0.194242,0.018291
...,...,...,...,...,...,...,...,...,...,...,...,...
460,Validation,XGBoost,Under,pc_GEIM800101_XGBoost_42_metrics,0.493305,0.493305,0.492349,0.488484,0.706751,0.242978,0.185545,0.031227
461,Validation,XGBoost,Under,pc_GEIM800105_XGBoost_42_metrics,0.495056,0.495056,0.492632,0.489707,0.719426,0.245125,0.881068,0.036625
462,Validation,XGBoost,Under,pc_JOND750101_XGBoost_42_metrics,0.478079,0.478079,0.475934,0.473937,0.682049,0.218847,0.850948,0.035446
463,Validation,XGBoost,Under,pc_KLEP840101_XGBoost_42_metrics,0.449520,0.449520,0.445638,0.441974,0.604540,0.176105,0.115326,0.034473
464,Validation,XGBoost,Under,pc_ROBB760113_XGBoost_42_metrics,0.430960,0.430960,0.430702,0.427348,0.626167,0.148321,1.011438,0.040485

In [113]:
mean_grouped.to_csv("resume_metrics.csv", index=False)