### Homology reduction of sequences

In [13]:
import pandas as pd
import sys
sys.path.insert(0, "../../")
from utils.filter_homology import HomologyReduction
filter_sequences = HomologyReduction()

In [14]:
df = pd.read_csv('../../data/not_outliers/notout_antiviral.csv')

In [15]:
df

,sequence,experimental_characteristics,half_life_seconds,length_sequence,target
0,AAAMSQVTN,Mammalian,15840.0,9,1
1,AACEVAKNLNESLIDLQELGKYEQYIKW,Mammalian,15840.0,28,1
2,AAGAVVNDL,Mammalian,15840.0,9,1
3,AAHLIDALYAEFLGGRVLTT,Mammalian,15840.0,20,1
4,AAHLIDALYAEFLGGRVLTTPVVHRALFYASAVLRQPFLAGVPSA,Mammalian,15840.0,45,1
...,...,...,...,...,...
1924,YVREHGVPIHADKYFEQVLK,Mammalian,10080.0,20,1
1925,YWILEYLWKVPFDFWRGV,E_coli,7200.0,18,0
1926,YWILEYLWKVPFDFWRGV,Mammalian,10080.0,18,1
1927,YWILEYLWKVPFDFWRGV,Yeast,36000.0,18,2
1928,YAGAVVNDL,E_coli,7200.0,9,0

In [16]:
df_high = df[df['target'] == 2]
df_mid = df[df['target'] == 1]
df_low = df[df['target'] == 0]

In [ ]:
df_low['quantil'] = pd.cut(df_low['half_life_seconds'], bins=4, labels=['Q1', 'Q2', 'Q3', 'Q4'])

print(df_low['quantil'].value_counts())

Q4    616
Q1    206
Q2    205
Q3      0
Name: cuartil, dtype: int64

In [23]:
df_low

,sequence,experimental_characteristics,half_life_seconds,length_sequence,target,cuartil
103,CAVACELKWESEFWRWTE,Mammalian,4320.0,18,0,Q2
104,CDVIALLACHLNT,Mammalian,4320.0,13,0,Q2
105,CDVIALLCHLNT,Mammalian,4320.0,12,0,Q2
106,CDVIALLCHLNTPSF,Mammalian,4320.0,15,0,Q2
107,CDVIALLCHLNTPSFNTTHYRESWY,Mammalian,4320.0,25,0,Q2
...,...,...,...,...,...,...
1918,YTSLIHSLIEEWQNQQEKNEQELLELDKWASLWNWF,E_coli,7200.0,36,0,Q4
1919,YTSLIHSLIEEYQNQQEKNEQELLELDKWASLWNWF,E_coli,7200.0,36,0,Q4
1922,YVREHGVPIHADKYFEQVLK,E_coli,7200.0,20,0,Q4
1925,YWILEYLWKVPFDFWRGV,E_coli,7200.0,18,0,Q4
1928,YAGAVVNDL,E_coli,7200.0,9,0,Q4

In [ ]:
filter_sequences.process(df=df[df['quantil'] == 'Q1'],
                         path_export="homology",
                         data_type="df_low_Q1",
                         value_filter=0.90,
                         len=4)

================================================================
Program: CD-HIT, V4.8.1 (+OpenMP), Aug 20 2021, 08:39:56
Command: cd-hit -i
         ../../data/homology/fasta_files/medium_data.fasta -o
         ../../data/homology/fasta_files/medium_data_filter.fasta
         -c 0.9 -l 4 -M 1000

Started: Tue May 27 12:47:21 2025
================================================================
                            Output
----------------------------------------------------------------
total seq: 629
longest and shortest : 48 and 5
Total letters: 11190
Sequences have been sorted

Approximated minimal memory consumption:
Sequence        : 0M
Buffer          : 1 X 10M = 10M
Table           : 1 X 65M = 65M
Miscellaneous   : 0M
Total           : 75M

Table limit with the given memory limit:
Max number of representatives: 4000000
Max number of word counting entries: 115505265

comparing sequences from          0  to        629

      629  finished        394  clusters

Approximated maximum memory consumption: 75M
writing new database
writing clustering information
program completed !

Total CPU time 0.04